### ISSUE TITLE
WARNING: gnome-web-photo is missing --> screenshots of websites will be disabled!

### ISSUE THREAD

**Issue by mozgbrasil** [popey/shutter-snap#7]
Good Morning

Who can help

I just installed the tool via snap

But I can't capture the browser that the tool simply closes but is active on the system monitor

Another case is that according to images that does not capture the url, showing several errors

    WARNING: gnome-web-photo is missing --> screenshots of websites will be disabled!

    INFO: gathering system information...

    Linux marcio-Inspiron-7520 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

    cat: /etc/issue: Permission denied

    Glib 1.320 
    Gtk2 1.2498 

    Glib built for 2.47.3, running with 2.48.2
    Gtk2 built for 2.24.29, running with 2.24.30

    Distorção de barril - /snap/shutter/27/share/shutter/resources/system/plugins/perl/spbardistortion/spbardistortion
    Gerar negativo - /snap/shutter/27/share/shutter/resources/system/plugins/perl/spnegate/spnegate
    Polaroid - /snap/shutter/27/share/shutter/resources/system/plugins/perl/sppolaroid/sppolaroid
    Redimensionar - /snap/shutter/27/share/shutter/resources/system/plugins/perl/spresize/spresize
    Sépia - /snap/shutter/27/share/shutter/resources/system/plugins/perl/spsepia/spsepia
    Sombra dura - /snap/shutter/27/share/shutter/resources/system/plugins/perl/spshadow/spshadow
    Marca d'água - /snap/shutter/27/share/shutter/resources/system/plugins/perl/spwatermark/spwatermark
    Escala de cinzas - /snap/shutter/27/share/shutter/resources/system/plugins/shell/spgrayscale/spgrayscale
    Deslocamento - /snap/shutter/27/share/shutter/resources/system/plugins/shell/spoffset/spoffset
    Elevar a borda - /snap/shutter/27/share/shutter/resources/system/plugins/shell/spraise/spraise
    Bordas suaves - /snap/shutter/27/share/shutter/resources/system/plugins/shell/spsoftedges/spsoftedges
    Borda em baixo relevo - /snap/shutter/27/share/shutter/resources/system/plugins/shell/spsunk/spsunk
    Papel rasgado - /snap/shutter/27/share/shutter/resources/system/plugins/shell/sptornedpaper/sptornedpaper
    Corte automático - /snap/shutter/27/share/shutter/resources/system/plugins/shell/sptrim/sptrim
    Current window manager: GNOME Shell
    Current window manager: GNOME Shell

    type_changed was emitted by widget Gtk2::ComboBox=HASH(0x1896128)

    (shutter:18607): GLib-GIO-WARNING **: Error creating IO channel for /proc/mounts: Permission denied (g-file-error-quark, 2)

    im_colors_changed was emitted by widget Gtk2::ComboBox=HASH(0x5691178)

    im_colors_toggled was emitted by widget Gtk2::CheckButton=HASH(0x5695df0)

    thumbnail_changed was emitted by widget Gtk2::HScale=HASH(0x5695ec8)

    thumbnail_toggled was emitted by widget Gtk2::CheckButton=HASH(0x5695f10)

    bordereffect_toggled was emitted by widget Gtk2::CheckButton=HASH(0x5695e20)

    bordereffect_changed was emitted by widget Gtk2::SpinButton=HASH(0x5696108)

    menu_delay_changed was emitted by widget Gtk2::SpinButton=HASH(0x1861048)

    hide_time_changed was emitted by widget Gtk2::SpinButton=HASH(0x5790a88)

    ns_changed was emitted by widget Gtk2::ComboBox=HASH(0x5790b00)

    web was emitted by widget global_keybinding
    3 Ns used in wild-card
    Searching for files with pattern: (?^u:\$name_(\d\d\d)\.png)
    Searching for files with pattern: (?^u:.{1,}_(\d\d\d)\.png)

    virtual website width: 1024
    Can't call method "get_children" on an undefined value at /snap/shutter/27/bin/shutter line 6333.

![2020-08-06_11-29-16_images_vertical](https://user-images.githubusercontent.com/17202780/89544124-1dbc2a00-d7d8-11ea-82f7-340c29fe99f9.png)

**Comment by tido-** [comment]
I did an upgrade from Mate 18.04 to 20.04 and then installed Shutter.
Debug Logs https://snapcraft.io/docs/debug-snaps  adds some more information, smells like an Apparmor issue. Shutter doesn't get permission to open any files. I cannot take a screenshot, because Shutter gets an ACCESS DENIED on my home-directory.
```
Sep 15 15:22:45 X470-ULTRA audit[4116]: AVC apparmor="DENIED" operation="capable" profile="/snap/core/9804/usr/lib/snapd/snap-confine" pid=4116 comm="snap-confine" capability=4  capname="fsetid"
Sep 15 15:22:45 X470-ULTRA kernel: kauditd_printk_skb: 33 callbacks suppressed
Sep 15 15:22:45 X470-ULTRA kernel: audit: type=1400 audit(1600176165.919:45): apparmor="DENIED" operation="capable" profile="/snap/core/9804/usr/lib/snapd/snap-confine" pid=4116 comm="snap-confine" capability=4  capname="fsetid"
Sep 15 15:22:46 X470-ULTRA audit[4192]: AVC apparmor="DENIED" operation="open" profile="snap.shutter.shutter" name="/media/Daten_1/" pid=4192 comm="head" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
Sep 15 15:22:46 X470-ULTRA kernel: audit: type=1400 audit(1600176166.439:46): apparmor="DENIED" operation="open" profile="snap.shutter.shutter" name="/media/Daten_1/" pid=4192 comm="head" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
Sep 15 15:22:46 X470-ULTRA audit[4211]: AVC apparmor="DENIED" operation="rmdir" profile="snap.shutter.shutter" name="/media/Daten_1/" pid=4211 comm="rmdir" requested_mask="d" denied_mask="d" fsuid=1000 ouid=0
Sep 15 15:22:46 X470-ULTRA kernel: audit: type=1400 audit(1600176166.475:47): apparmor="DENIED" operation="rmdir" profile="snap.shutter.shutter" name="/media/Daten_1/" pid=4211 comm="rmdir" requested_mask="d" denied_mask="d" fsuid=1000 ouid=0
and so on...
```

Edit, some more information according to the trouble shooting

```
$ sudo apparmor_status |grep snap
   /snap/core/9804/usr/lib/snapd/snap-confine
   /snap/core/9804/usr/lib/snapd/snap-confine//mount-namespace-capture-helper
   /usr/lib/snapd/snap-confine
   /usr/lib/snapd/snap-confine//mount-namespace-capture-helper
   snap-update-ns.core
   snap-update-ns.pulsemixer
   snap-update-ns.shutter
   snap-update-ns.software-boutique
   snap-update-ns.ubports-installer
   snap-update-ns.ubuntu-mate-welcome
   snap.core.hook.configure
   snap.pulsemixer.pulsemixer
   snap.shutter.shutter
   snap.ubports-installer.ubports-installer
   snap.software-boutique.software-boutique
   snap.ubuntu-mate-welcome.hook.install
   snap.ubuntu-mate-welcome.hook.post-refresh
   snap.ubuntu-mate-welcome.hook.remove
   snap.ubuntu-mate-welcome.software-boutique
   snap.ubuntu-mate-welcome.ubuntu-mate-welcome
```

Edit 26. Sept. 2020:
```
$ snap connections shutter
Benutzeroberfläche      Plug                     Slot                              Notizen
audio-playback          shutter:audio-playback   :audio-playback                   -
content[gtk-2-engines]  shutter:gtk-2-engines    gtk2-common-themes:gtk-2-engines  -
content[gtk-2-themes]   shutter:gtk-2-themes     gtk-common-themes:gtk-2-themes    -
content[icon-themes]    shutter:icon-themes      gtk-common-themes:icon-themes     -
dbus                    -                        shutter:dbus-shutter              -
desktop                 shutter:desktop          :desktop                          -
desktop-legacy          shutter:desktop-legacy   :desktop-legacy                   -
gsettings               shutter:gsettings        :gsettings                        -
home                    shutter:home             :home                             -
network                 shutter:network          :network                          -
removable-media         shutter:removable-media  -                                 -
unity7                  shutter:unity7           :unity7                           -
x11                     shutter:x11              :x11                              -
```
@popey, do you have it running on an 20.04?

**Comment by tido-** [comment]
Here is how I solved my problem - there may be two ways:
`sudo snap connect shutter:removable-media :removable-media`

or install the snap-store and get a graphical-interface to change permission.
`sudo snap install snap-store`

![grafik](https://user-images.githubusercontent.com/10658438/94347558-9ea7dd00-0035-11eb-89a2-0aa5e5c46266.png)
